#pragma once
#include "FormulaDef.h"
#include "SymbolsDef.h"


//一元操作符
DEFINE_SYMBOLS_START(UnaryOpSymbols, SFI)
	ADD("+", SFI_POSITIVE)
	ADD("-", SFI_NEGATIVE)
	ADD("!", SFI_NOT)
	ADD("~", SFI_BIT_NOT)
DEFINE_SYMBOLS_END

//加减操作符
DEFINE_SYMBOLS_START(AdditiveOpSymbols, SFI)
	ADD("+", SFI_PLUS)
	ADD("-", SFI_MINUS)
DEFINE_SYMBOLS_END

//乘除取余操作符
DEFINE_SYMBOLS_START(MultiplicativeOpSymbols, SFI)
	ADD("*", SFI_MUL)
	ADD("/", SFI_DIV)
	ADD("%", SFI_MOD)
DEFINE_SYMBOLS_END


DEFINE_SYMBOLS_START(RelationalOpSymbols, SFI)
	ADD("<", SFI_LESS)
	ADD("<=", SFI_LESS_EQU)
	ADD(">", SFI_GREATER)
	ADD(">=", SFI_GREATER_EQU)
DEFINE_SYMBOLS_END

DEFINE_SYMBOLS_START(BitAndOpSymbols, SFI)
	ADD("&", SFI_BIT_AND)
DEFINE_SYMBOLS_END

DEFINE_SYMBOLS_START(BitXOROpSymbols, SFI)
	ADD("^", SFI_BIT_XOR)
DEFINE_SYMBOLS_END

DEFINE_SYMBOLS_START(BitOrOpSymbols, SFI)
	ADD("|", SFI_BIT_OR)
DEFINE_SYMBOLS_END

DEFINE_SYMBOLS_START(EqulityOpSymbols, SFI)
	ADD("=", SFI_EQU)
	ADD("<>", SFI_NOT_EQU)
DEFINE_SYMBOLS_END

DEFINE_SYMBOLS_START(LogicalOrOpSymbols, SFI)
	ADD("||", SFI_OR)
	ADD("or", SFI_OR)
DEFINE_SYMBOLS_END


DEFINE_SYMBOLS_START(LogicalAndOpSymbols, SFI)
	ADD("&&", SFI_AND)
	ADD("and", SFI_AND)
DEFINE_SYMBOLS_END